### ISSUE TITLE
Trinidad and Tobago - Errno 22 - Heavy Rains?.csv

### ISSUE THREAD

**Issue by dadelforge** [COMP0016-IFRC-Team5/data-downloader#1]
While running the data downloader example.py file, I got this error:

> Traceback (most recent call last):
  File "****\data-downloader\example.py", line 10, in <module>
    csv_downloader.start_download(target_dir, mode=0b011)
  File "****\data-downloader\csv_downloader\__init__.py", line 7, in start_download
    start(target_dir, mode)
  File "****\data-downloader\csv_downloader\_exec.py", line 9, in start
    csv_crawler.run(mode)
  File "****\data-downloader\csv_downloader\_csv_crawler.py", line 189, in run
    self.download_country_data(country, disasters,
  File "****\data-downloader\csv_downloader\_csv_crawler.py", line 156, in download_country_data
    CSVCrawler.download_disaster_csv(country, disaster,
  File "****\DesInventar\data-downloader\csv_downloader\_csv_crawler.py", line 143, in download_disaster_csv
    with open(filepath, 'wb') as f:
OSError: [Errno 22] Invalid argument: '***/data/raw_csv_files/Trinidad and Tobago_tto/Heavy Rains?.csv'

I checked and `Heavy Rains?.csv` does not exist. For Trinidad and Tobago, there are two types `Heavy rains` with 22 events and `Heavy Rains?` with [one event](https://www.desinventar.net/DesInventar/showdatacard.jsp?clave=1168&nStart=0). The `Heavy Rains.csv` file has been created but is completely blank inside. 

It could be that, during the processing, the `?` his ignored and the similarity of the event type names caused the issue?

**Comment by DekunZhang** [comment]
Hello @dadelforge Sorry for the late reply since I was working on my final exams last month. Could you give me some details about how you encountered this problem? Can this problem be solved by rerunning the script? Thank you very much! Looking forward to your reply.
